---
apiVersion: v1
kind: Template
metadata:
  name: sealights-mcp
parameters:
- name: IMAGE
  value: quay.io/redhat-ai-tools/sealights-mcp
- name: IMAGE_TAG
  value: latest
- name: MCP_TRANSPORT
  value: sse
- name: FASTMCP_HOST
  value: "0.0.0.0"
- name: CERT_MANAGER_ISSUER_NAME
  value: letsencrypt-dns
- name: MCP_HOST
  value: sealights-mcp.example.com
- name: SEALIGHTS_DOMAIN
  value: https://your-domain.sealights.co
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: sealights-mcp
    name: sealights-mcp
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: sealights-mcp
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: sealights-mcp
      spec:
        containers:
        - name: sealights-mcp
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          env:
          - name: MCP_TRANSPORT
            value: ${MCP_TRANSPORT}
          - name: FASTMCP_HOST
            value: ${FASTMCP_HOST}
          - name: SEALIGHTS_DOMAIN
            value: ${SEALIGHTS_DOMAIN}
          ports:
          - containerPort: 8000
            protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    name: sealights-mcp
    labels:
      app: sealights-mcp
  spec:
    selector:
      app: sealights-mcp
    ports:
      - protocol: TCP
        port: 8000
        targetPort: 8000
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      cert-manager.io/issuer-kind: ClusterIssuer
      cert-manager.io/issuer-name: ${CERT_MANAGER_ISSUER_NAME}
    name: sealights-mcp
    labels:
      app: sealights-mcp
  spec:
    host: ${MCP_HOST}
    to:
      kind: Service
      name: sealights-mcp
    port:
      targetPort: 8000
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
